spring.application.name=NoPainNoMain
# URL de conexión (localhost porque el puerto 5432 está mapeado a tu PC)
spring.datasource.url=jdbc:postgresql://localhost:5432/nopainnomain_db
spring.datasource.username=Admin2026
spring.datasource.password=MRJybs28

# Configuración extra para que Spring Boot cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true